
vim.keymap.set("n", "<leader>gg", function()
	vim.cmd(':FloatermNew --width=0.70 --wintype=vsplit  lazygit ')
end)
vim.keymap.set("n", "<leader>tt", function()
	vim.cmd(':FloatermToggle')
end)
vim.keymap.set("t", "<C-t>", function()
	vim.cmd(':FloatermToggle')
end)
